apiVersion: cstor.openebs.io/v1
kind: CStorPoolCluster
metadata:
 name: cstor-disk-pool
 namespace: openebs
spec:
 pools:
   - nodeSelector:
       kubernetes.io/hostname: "pool-4sf660a34-fk7pp"
     dataRaidGroups:
       - blockDevices:
           - blockDeviceName: "blockdevice-2b7739a501b4c203a39acaa6c662508c"
     poolConfig:
       dataRaidGroupType: "stripe"

