apiVersion: cstor.openebs.io/v1
kind: CStorPoolCluster
metadata:
 name: cstor-disk-pool-1
 namespace: openebs
spec:
 pools:
   - nodeSelector:
       kubernetes.io/hostname: "pool-4sf660a34-fk7ps"
     dataRaidGroups:
       - blockDevices:
           - blockDeviceName: "blockdevice-3a4007a2292fe1c860e328662ec88893"
     poolConfig:
       dataRaidGroupType: "stripe"

   - nodeSelector:
       kubernetes.io/hostname: "pool-4sf660a34-fk7pp"
     dataRaidGroups:
       - blockDevices:
           - blockDeviceName: "blockdevice-52724ac59f34bb643f87003f93d4c11b"
     poolConfig:
       dataRaidGroupType: "stripe"

